name: Docker

on:
  workflow_call:
    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Docker Build
        uses: docker/setup-buildx-action@v3.11.1

      - name: Download a Build Artifact
        uses: actions/download-artifact@v5.0.0
        with:
          name: app  

      - name: Docker Login
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker images

        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: rayy2018/go_ci:${{ github.ref_name }}
                
        


